### ISSUE TITLE
Throw exception "Bluetooth Permission not granted" even permission granted

### ISSUE THREAD

**Issue by alisherbu** [rohitsangwan01/ble_peripheral#1]
**When I call intitialize method, it throws this exception:**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Exception, java.lang.Exception: Bluetooth Permission not granted, Cause: null, Stacktrace: java.lang.Exception: Bluetooth Permission not granted
                                                                                                    	at com.rohit.ble_peripheral.BlePeripheralPlugin.initialize(BlePeripheralPlugin.kt:71)
                                                                                                    	at com.rohit.ble_peripheral.BlePeripheralChannel$Companion.setUp$lambda$1$lambda$0(BlePeripheral.g.kt:277)
                                                                                                    	at com.rohit.ble_peripheral.BlePeripheralChannel$Companion.$r8$lambda$MnuKy-RVGk0M2vNjak8GFv1UlD4(Unknown Source:0)
                                                                                                    	at com.rohit.ble_peripheral.BlePeripheralChannel$Companion$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
                                                                                                    	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:219)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    , null)
                                                                                                    #0      BlePeripheralChannel.initialize (package:ble_peripheral/src/ble_peripheral.g.dart:249:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      BlePeripheral.initialize (package:ble_peripheral/ble_peripheral.dart:11:5)
                                                                                                    <asynchronous suspension>

**Comment by rohitsangwan01** [comment]
@alisherbu please ask bluetooth permissions before initializing

**Comment by alisherbu** [comment]
I'm asked. 
  @override
  Future<void> initialize() async {
    printLog('BluetoothService', (await Permission.bluetooth.request().isGranted));
    printLog('BluetoothService', (await Permission.bluetoothAdvertise.request().isGranted));
    printLog('BluetoothService', (await Permission.bluetoothConnect.request().isGranted));
    printLog('BluetoothService', (await Permission.bluetoothScan.request().isGranted));
    // await blePeripheral.initialize();
  }

Permission handler said this:
  Bluetooth permission missing in manifest
  BluetoothService: false
  BluetoothService: true
  BluetoothService: true
  BluetoothService: true

I declared all permissions in manifest

**Comment by rohitsangwan01** [comment]
@alisherbu have you tried example app ?

**Comment by alisherbu** [comment]
Yes, the example app is working well. But when I use library from other app and call blePeripheral.initialize(), it crashes with PlatformException(Exception, java.lang.Exception: Bluetooth Permission not granted. But I gonna try to find where is the problem. It may my mistake

**Comment by rohitsangwan01** [comment]
@alisherbu if example app works , then you are probably missing something in your project
and you are getting Bluetooth Permission issue, then you have to ask bluetooth permission in flutter side using PermissionHandler plugin , and make sure you have added the required permissions in Manifest

**Comment by alisherbu** [comment]
Problem has been fixed. But I'm shocked. I have just replaced it

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
 
to your app permissions order

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />

I don't understand

**Comment by rohitsangwan01** [comment]
@alisherbu thats strange, ok i will investigate this later, well i guess we can close this issue now

**Comment by alisherbu** [comment]
Yes, you can. I think this not issue. My purpose was just ask help. Thank you for your time
